services:
  db:
    image: postgres:16-alpine
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecret
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
        - botnet

  web-app:
    image: jonrobin2/event-tracker:r1
    container_name: event-tracker
    depends_on:
      - db
    ports:
      - "12345:12345"
      - "8080:8080"
    environment:
      PORT: 12345
      EVENT_TRACKER_IN_CONTAINER: yes
    networks:
        - botnet

volumes:
    postgres_data:

networks:
    botnet:
        driver: bridge
